### ISSUE TITLE
When vim exit, stop_nextword error

### ISSUE THREAD

**Issue by tsuyoshicho** [high-moctane/asyncomplete-nextword.vim#2]
verbose=3 verboselog result

last empty scratch buffer, `:qa` execute.

```log
VimLeave Autocommands for "*" の処理中にエラーが検出されました:
E486: パターンは見つかりませんでした: stop_nextword()
```

https://github.com/high-moctane/asyncomplete-nextword.vim/blob/b169e5f318dcb87ab8353d7f23b29d2b640dd617/autoload/asyncomplete/sources/nextword.vim#L1-L4

https://github.com/high-moctane/asyncomplete-nextword.vim/blob/b169e5f318dcb87ab8353d7f23b29d2b640dd617/autoload/asyncomplete/sources/nextword.vim#L60-L62

not set call s:stop_nextword()

**Comment by tsuyoshicho** [comment]
#1 related

**Comment by high-moctane** [comment]
Merged the pull request.
Thank you for your issue (｀･ω･´)！
