### ISSUE TITLE
use allowlist for asyncomplete 

### ISSUE THREAD

**Issue by prabirshrestha** [high-moctane/asyncomplete-nextword.vim#3]
ref: prabirshrestha/asyncomplete.vim#204

**Comment by high-moctane** [comment]
No problem with this plugin.

**Comment by prabirshrestha** [comment]
Not a problem with plug-in but it is mentioned in README.md which needs to be updated.

**Comment by high-moctane** [comment]
Sorry, I overlooked README.md.

**Comment by high-moctane** [comment]
#4
